FROM melezhik/sparrow:ubuntu_arm

RUN sudo apt-get update && sudo apt install python3 -yq
RUN echo OK && zef install --/test --force-install https://github.com/melezhik/Sparrow6.git
RUN echo OK && zef install --/test --force-install https://github.com/melezhik/Sparky-Job-Api.git
RUN git config --global advice.detachedHead false
