FROM debian:latest

RUN apt-get update && apt install python3 -yq wget git libssl-dev procps nano curl

RUN git config --global advice.detachedHead false

RUN mkdir -p  ~/projects/rakupp && cd ~/projects/rakupp && \
wget https://github.com/ash/rakupp/releases/download/v3.23.0/rakupp-linux-x86_64.tar.gz \
&& tar -xzf rakupp-linux-x86_64.tar.gz && cd rakupp

ENV PATH=/root/projects/rakupp/rakupp/bin/:/root/.raku/bin:$PATH

ENV SP6_RAKU_COMP=rakupp

RUN rakupp install --no-test JSON::Name JSON::Fast File::Directory::Tree

RUN rakupp install --no-test Sparrow6 Sparky-Job-Api

RUN raku -MSparrow6::Task::Repository -e Sparrow6::Task::Repository::Api.new.index-update

RUN echo 'export PATH=/root/projects/rakupp/rakupp/bin/:/root/.raku/bin:$PATH' >> ~/.profile

RUN echo 'SP6_RAKU_COMP=rakupp' >> ~/.profile
