package job

import (
	"dsci_runner/types"
	"dsci_runner/utils"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"strings"
	"path/filepath"
	"errors"

)

func JobQueueFs(r types.JobRequest) {

	project := r.Config.Project
	
	job_id := r.Config.JobId

	fmt.Printf("start job for project: %s, job_id: %s\n", project, job_id)

	jsonData, err := json.MarshalIndent(r.Config, "", "  ") // Use MarshalIndent for pretty printing

	//log.Printf("JobQueueFs queue job: r.Config: %s\n",jsonData)

	sparky_project_dir := utils.CreateSparkyProjectDir(project)

	cache_dir := utils.CreateSparkyCacheDir(job_id)

	jsonData, err = json.MarshalIndent(r.SparrowdoConfig, "", "  ") // Use MarshalIndent for pretty printing

	if err != nil {
		log.Fatal("Error marshaling to JSON:", err)
	}

	err = os.WriteFile(fmt.Sprintf("%s/config.json", cache_dir), jsonData, 0644)
	if err != nil {
		log.Fatal(err)
	}

	r.Trigger.Cwd = cache_dir

	if r.Config.Sparrowdo.Localhost {
		r.Trigger.Sparrowdo.Docker = ""
		r.Trigger.Sparrowdo.Host = ""
	} else if r.Config.Sparrowdo.Host != "" {
		r.Trigger.Sparrowdo.Docker = ""
		r.Trigger.Sparrowdo.Localhost = false
	} else if r.Config.Sparrowdo.Docker != "" {
		r.Trigger.Sparrowdo.Localhost = false
		r.Trigger.Sparrowdo.Host = ""
	}

	if r.Config.Sparrowdo.Sudo {
		r.Trigger.Sparrowdo.NoSudo = false
		r.Trigger.Sparrowdo.Sudo = true
	}

	if r.Config.Sparrowdo.NoSudo {
		r.Trigger.Sparrowdo.Sudo = false
		r.Trigger.Sparrowdo.NoSudo = true
	}

	if r.Config.Description != "" {
		r.Trigger.Description = r.Config.Description
	} else {
		r.Trigger.Description = "spawned job"
	}

	var tags []string

	for k, vv := range r.Config.Tags {
		switch v := vv.(type) {
		case string:
			v_safe := strings.ReplaceAll(v, ",", "___comma___")
			v_safe = strings.ReplaceAll(v_safe, "=", "___eq___")
			tags = append(tags, fmt.Sprintf("%s=%s", k, v_safe))
		case int:
			tags = append(tags, fmt.Sprintf("%s=%d", k, v))
		case bool:
			tags = append(tags, fmt.Sprintf("%s", k))
		}
	}

	if len(tags) != 0 {
		fmt.Printf(
			"JobQueueFs: append tags from Config.Tags to Trigger.Sparrowdo.Tags string: %s\n",
			strings.Join(tags, ","),
		)
		r.Trigger.Sparrowdo.Tags = r.Trigger.Sparrowdo.Tags + strings.Join(tags, ",")
	}

	if r.SparrowdoConfig != nil {
		r.Trigger.Sparrowdo.Conf = "config.json"
	}

	fmt.Printf(
		"job-queue-fs: create trigger file: %s/.triggers/%s\n",
		sparky_project_dir,
		job_id,
	)

	jsonData, err = json.MarshalIndent(r.Trigger, "", "  ") // Use MarshalIndent for pretty printing

	err = os.WriteFile(fmt.Sprintf("%s/.triggers/%s.json", sparky_project_dir, job_id), jsonData, 0644)

	if err != nil {
		log.Fatalf("JobQueueFs: can't create trigger file: %s",err)
	}

	path := fmt.Sprintf("%s/sparrowfile",sparky_project_dir)

	if _, err := os.Stat(path); errors.Is(err, os.ErrNotExist) {
		err = os.WriteFile(path, []byte("# dummy file, generated by dsci"), 0644)
		if err != nil {
			log.Fatalf("JobQueueFs: can't create sparrowfile: %s",err)
		}
	}

	err = os.WriteFile(fmt.Sprintf("%s/sparrowfile", cache_dir), []byte(r.Sparrowfile), 0644)

	if err != nil {
		log.Fatal(err)
	}
  
	log.Printf("JobQueueFs queue job: %s\ncache dir: %s\n",jsonData,cache_dir)

}

func PutJobStash ( p string, job_id string, data interface{}) {

	utils.CreateSparkyStashDir(p)

	path := filepath.Join(utils.SparkyStashDir(p), job_id)

	file, err := os.Create(path)
	if err != nil {
		log.Fatalf("PutJobStash: Error creating file:", err)
	}
	defer file.Close()

	encoder := json.NewEncoder(file)
	
	encoder.SetIndent("", "  ") // Optional: prettify

	err = encoder.Encode(data)

	if err != nil {
		log.Fatalf("Error encoding JSON:", err)
	}
}

func GetJobStash ( p string, job_id string) string {
	path := filepath.Join(utils.SparkyStashDir(p), job_id)

	if _, err := os.Stat(path); errors.Is(err, os.ErrNotExist) {
		return "{}"
	}

    dat, err := os.ReadFile(path)

	if err != nil {
		log.Fatalf("Error reading file:", err)
	}
	return string(dat)
}

func GetJobFile ( p string, job_id string, filename string) string {

	path := filepath.Join(utils.SparkyFilesDir(p),job_id,filename)

    dat, err := os.ReadFile(path)

	if err != nil {
		log.Fatalf("Error reading file:", err)
	}
	return string(dat)
}

func GetSparkyScenarioFile (p string, filename string) string {

	path := filepath.Join(utils.SparkyProjectDir(p),filename)

    dat, err := os.ReadFile(path)

	if err != nil {
		log.Fatalf("GetSparkyScenarioFile: Error reading file:", err)
	}
	return string(dat)
}

func GetSparrowdoConfig (p string, filename string) interface{} {

	path := filepath.Join(utils.SparkyProjectDir(p),filename)

    dat, err := os.ReadFile(path)

	if err != nil {
		log.Fatalf("GetSparrowdoConfig: Error reading file:", err)
	}

	var c interface{}

	err = json.Unmarshal(dat, &c)

	if err != nil {
		log.Fatalf("GetSparrowdoConfig: error unmarshaling JSON: %v", err)
	}

	return c
}
